-- SAT-J Ent Phase 6: trusted transfer lifecycle and inventory transactions.
create function public.next_transfer_number() returns text language plpgsql security definer set search_path='' as $$
declare yr integer:=extract(year from now())::integer;n bigint;
begin insert into public.transfer_number_sequences(year,last_number) values(yr,1) on conflict(year) do update set last_number=public.transfer_number_sequences.last_number+1 returning last_number into n;return 'TRF-'||yr||'-'||lpad(n::text,6,'0');end;$$;

create function public.active_transfer_branches() returns table(id uuid,code text,name text) language sql stable security definer set search_path='' as $$
 select b.id,b.code,b.name from public.branches b where b.is_active and public.has_permission('transfers.read') order by b.name
$$;

create function public.create_transfer(target_source uuid,target_destination uuid,transfer_notes text,submit_now boolean,items jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare transfer_id uuid;entry jsonb;variant uuid;qty numeric;product_label text;variant_label text;sku_label text;unit_label text;
begin
 if not public.has_permission('transfers.create') or not public.can_access_branch(target_source) then raise exception 'You do not have permission to create a transfer from this branch';end if;
 if target_source=target_destination then raise exception 'Source and destination branches must be different';end if;
 if (select count(*) from public.branches where id in(target_source,target_destination) and is_active)<>2 then raise exception 'Transfers require two active branches';end if;
 if jsonb_typeof(items)<>'array' or jsonb_array_length(items)=0 then raise exception 'At least one transfer item is required';end if;
 if exists(select 1 from(select value->>'variant_id' from jsonb_array_elements(items) group by 1 having count(*)>1)d) then raise exception 'Duplicate variants are not allowed';end if;
 insert into public.stock_transfers(transfer_number,source_branch_id,destination_branch_id,status,notes,created_by,requested_by,requested_at)
 values(public.next_transfer_number(),target_source,target_destination,case when submit_now then 'REQUESTED'::public.stock_transfer_status else 'DRAFT'::public.stock_transfer_status end,nullif(trim(transfer_notes),''),auth.uid(),case when submit_now then auth.uid() end,case when submit_now then now() end) returning id into transfer_id;
 for entry in select value from jsonb_array_elements(items) loop
  variant:=(entry->>'variant_id')::uuid;qty:=(entry->>'quantity')::numeric;perform public.validate_inventory_quantity(variant,qty,false);
  select p.name,v.name,v.sku,u.symbol into product_label,variant_label,sku_label,unit_label from public.product_variants v join public.products p on p.id=v.product_id join public.units_of_measure u on u.id=p.unit_of_measure_id where v.id=variant and v.is_active and p.status='ACTIVE';if not found then raise exception 'Choose an active product variant';end if;
  insert into public.stock_transfer_items(transfer_id,variant_id,requested_quantity,product_name_snapshot,variant_name_snapshot,sku_snapshot,unit_snapshot,notes) values(transfer_id,variant,qty,product_label,variant_label,sku_label,unit_label,nullif(trim(entry->>'notes'),''));
 end loop;
 insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),target_source,'transfer.created','stock_transfers',transfer_id,jsonb_build_object('source_branch_id',target_source,'destination_branch_id',target_destination,'item_count',jsonb_array_length(items),'submitted',submit_now));
 if submit_now then insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),target_source,'transfer.requested','stock_transfers',transfer_id,jsonb_build_object('item_count',jsonb_array_length(items)));end if;return transfer_id;
end;$$;

create function public.update_draft_transfer(target_transfer uuid,target_source uuid,target_destination uuid,transfer_notes text,items jsonb) returns void language plpgsql security definer set search_path='' as $$
declare header public.stock_transfers%rowtype;entry jsonb;variant uuid;qty numeric;product_label text;variant_label text;sku_label text;unit_label text;
begin select * into header from public.stock_transfers where id=target_transfer for update;if not found then raise exception 'Transfer not found';end if;
 if header.status<>'DRAFT' then raise exception 'Only draft transfers can be edited';end if;if not public.has_permission('transfers.create') or not public.can_access_branch(target_source) then raise exception 'You do not have permission to edit this transfer';end if;
 if target_source=target_destination then raise exception 'Source and destination branches must be different';end if;if (select count(*) from public.branches where id in(target_source,target_destination) and is_active)<>2 then raise exception 'Transfers require two active branches';end if;
 if jsonb_typeof(items)<>'array' or jsonb_array_length(items)=0 then raise exception 'At least one transfer item is required';end if;if exists(select 1 from(select value->>'variant_id' from jsonb_array_elements(items) group by 1 having count(*)>1)d) then raise exception 'Duplicate variants are not allowed';end if;
 update public.stock_transfers set source_branch_id=target_source,destination_branch_id=target_destination,notes=nullif(trim(transfer_notes),'') where id=header.id;delete from public.stock_transfer_items where transfer_id=header.id;
 for entry in select value from jsonb_array_elements(items) loop variant:=(entry->>'variant_id')::uuid;qty:=(entry->>'quantity')::numeric;perform public.validate_inventory_quantity(variant,qty,false);select p.name,v.name,v.sku,u.symbol into product_label,variant_label,sku_label,unit_label from public.product_variants v join public.products p on p.id=v.product_id join public.units_of_measure u on u.id=p.unit_of_measure_id where v.id=variant and v.is_active and p.status='ACTIVE';if not found then raise exception 'Choose an active product variant';end if;insert into public.stock_transfer_items(transfer_id,variant_id,requested_quantity,product_name_snapshot,variant_name_snapshot,sku_snapshot,unit_snapshot,notes) values(header.id,variant,qty,product_label,variant_label,sku_label,unit_label,nullif(trim(entry->>'notes'),''));end loop;
 insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),target_source,'transfer.updated','stock_transfers',header.id,jsonb_build_object('item_count',jsonb_array_length(items)));
end;$$;

create function public.request_transfer(target_transfer uuid) returns void language plpgsql security definer set search_path='' as $$
declare header public.stock_transfers%rowtype;begin select * into header from public.stock_transfers where id=target_transfer for update;if not found then raise exception 'Transfer not found';end if;if header.status<>'DRAFT' then raise exception 'Only a draft transfer can be submitted';end if;if not public.has_permission('transfers.create') or not public.can_access_branch(header.source_branch_id) then raise exception 'You do not have permission to submit this transfer';end if;if not exists(select 1 from public.stock_transfer_items where transfer_id=header.id) then raise exception 'At least one transfer item is required';end if;update public.stock_transfers set status='REQUESTED',requested_by=auth.uid(),requested_at=now() where id=header.id;insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.source_branch_id,'transfer.requested','stock_transfers',header.id,jsonb_build_object('transfer_number',header.transfer_number));end;$$;

create function public.approve_transfer(target_transfer uuid) returns void language plpgsql security definer set search_path='' as $$
declare header public.stock_transfers%rowtype;item public.stock_transfer_items%rowtype;begin select * into header from public.stock_transfers where id=target_transfer for update;if not found then raise exception 'Transfer not found';end if;if header.status<>'REQUESTED' then raise exception 'Only a requested transfer can be approved';end if;if not public.has_permission('transfers.approve') or not public.can_access_branch(header.source_branch_id) then raise exception 'Only an authorized source branch manager can approve this transfer';end if;for item in select * from public.stock_transfer_items where transfer_id=header.id loop perform public.validate_inventory_quantity(item.variant_id,item.requested_quantity,false);end loop;update public.stock_transfer_items set approved_quantity=requested_quantity where transfer_id=header.id;update public.stock_transfers set status='APPROVED',approved_by=auth.uid(),approved_at=now() where id=header.id;insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.source_branch_id,'transfer.approved','stock_transfers',header.id,jsonb_build_object('transfer_number',header.transfer_number));end;$$;

create function public.dispatch_transfer(target_transfer uuid,operation_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare header public.stock_transfers%rowtype;item public.stock_transfer_items%rowtype;movement uuid;
begin if operation_id is null then raise exception 'A dispatch operation identifier is required';end if;select * into header from public.stock_transfers where dispatch_operation_key=operation_id;if found then return header.id;end if;select * into header from public.stock_transfers where id=target_transfer for update;if not found then raise exception 'Transfer not found';end if;if header.status<>'APPROVED' then raise exception 'Only an approved transfer can be dispatched';end if;if not public.has_permission('transfers.dispatch') or not public.can_access_branch(header.source_branch_id) then raise exception 'You do not have permission to dispatch stock from the source branch';end if;
 for item in select * from public.stock_transfer_items where transfer_id=header.id order by variant_id loop if item.approved_quantity is null then raise exception 'Every item must be approved before dispatch';end if;perform public.validate_inventory_quantity(item.variant_id,item.approved_quantity,false);movement:=public.inventory_apply_movement(header.source_branch_id,item.variant_id,'TRANSFER_OUT',-item.approved_quantity,'STOCK_TRANSFER',header.id,item.id::text,header.transfer_number||' · '||header.source_branch_id||' → '||header.destination_branch_id);update public.stock_transfer_items set dispatched_quantity=item.approved_quantity,transfer_out_movement_id=movement where id=item.id;end loop;
 update public.stock_transfers set status='DISPATCHED',dispatch_operation_key=operation_id,dispatched_by=auth.uid(),dispatched_at=now() where id=header.id;insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.source_branch_id,'transfer.dispatched','stock_transfers',header.id,jsonb_build_object('transfer_number',header.transfer_number,'destination_branch_id',header.destination_branch_id,'item_count',(select count(*) from public.stock_transfer_items where transfer_id=header.id)));return header.id;
end;$$;

create function public.receive_transfer(target_transfer uuid,operation_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare header public.stock_transfers%rowtype;item public.stock_transfer_items%rowtype;movement uuid;
begin if operation_id is null then raise exception 'A receipt operation identifier is required';end if;select * into header from public.stock_transfers where receive_operation_key=operation_id;if found then return header.id;end if;select * into header from public.stock_transfers where id=target_transfer for update;if not found then raise exception 'Transfer not found';end if;if header.status<>'DISPATCHED' then raise exception 'Only a dispatched transfer can be received';end if;if not public.has_permission('transfers.receive') or not public.can_access_branch(header.destination_branch_id) then raise exception 'Only the destination branch can confirm receipt';end if;
 for item in select * from public.stock_transfer_items where transfer_id=header.id order by variant_id loop if item.dispatched_quantity<=0 or item.transfer_out_movement_id is null then raise exception 'Every item must be dispatched before receipt';end if;movement:=public.inventory_apply_movement(header.destination_branch_id,item.variant_id,'TRANSFER_IN',item.dispatched_quantity,'STOCK_TRANSFER',header.id,item.id::text,header.transfer_number||' · '||header.source_branch_id||' → '||header.destination_branch_id);update public.stock_transfer_items set received_quantity=item.dispatched_quantity,transfer_in_movement_id=movement where id=item.id;end loop;
 update public.stock_transfers set status='RECEIVED',receive_operation_key=operation_id,received_by=auth.uid(),received_at=now() where id=header.id;insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.destination_branch_id,'transfer.received','stock_transfers',header.id,jsonb_build_object('transfer_number',header.transfer_number,'source_branch_id',header.source_branch_id,'item_count',(select count(*) from public.stock_transfer_items where transfer_id=header.id)));return header.id;
end;$$;

create function public.cancel_transfer(target_transfer uuid,reason text) returns void language plpgsql security definer set search_path='' as $$
declare header public.stock_transfers%rowtype;begin select * into header from public.stock_transfers where id=target_transfer for update;if not found then raise exception 'Transfer not found';end if;if header.status not in('DRAFT','REQUESTED','APPROVED') then raise exception 'A dispatched transfer cannot be cancelled';end if;if not public.has_permission('transfers.cancel') or not public.can_access_branch(header.source_branch_id) then raise exception 'You do not have permission to cancel this transfer';end if;if char_length(trim(coalesce(reason,'')))<3 then raise exception 'A cancellation reason is required';end if;update public.stock_transfers set status='CANCELLED',cancelled_by=auth.uid(),cancelled_at=now(),cancellation_reason=trim(reason) where id=header.id;insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.source_branch_id,'transfer.cancelled','stock_transfers',header.id,jsonb_build_object('transfer_number',header.transfer_number,'reason',trim(reason)));end;$$;

revoke all on function public.next_transfer_number(),public.active_transfer_branches(),public.create_transfer(uuid,uuid,text,boolean,jsonb),public.update_draft_transfer(uuid,uuid,uuid,text,jsonb),public.request_transfer(uuid),public.approve_transfer(uuid),public.dispatch_transfer(uuid,uuid),public.receive_transfer(uuid,uuid),public.cancel_transfer(uuid,text) from public;
grant execute on function public.active_transfer_branches(),public.create_transfer(uuid,uuid,text,boolean,jsonb),public.update_draft_transfer(uuid,uuid,uuid,text,jsonb),public.request_transfer(uuid),public.approve_transfer(uuid),public.dispatch_transfer(uuid,uuid),public.receive_transfer(uuid,uuid),public.cancel_transfer(uuid,text) to authenticated;
