-- SAT-J Ent Phase 5: trusted customer, sale, payment and reversal transactions.
create function public.next_sales_number(kind text) returns text language plpgsql security definer set search_path='' as $$
declare yr integer:=extract(year from now())::integer;n bigint;
begin if kind not in('CUS','SAL','RCP','CPY') then raise exception 'Invalid document type';end if;
 insert into public.sales_number_sequences(year,document_type,last_number) values(yr,kind,1) on conflict(year,document_type) do update set last_number=public.sales_number_sequences.last_number+1 returning last_number into n;
 if kind='CUS' then return 'CUS-'||lpad(n::text,6,'0');end if;return kind||'-'||yr||'-'||lpad(n::text,6,'0');end;$$;

create function public.resolve_selling_price(target_variant uuid,target_branch uuid,target_price_type public.price_type default 'RETAIL',at_time timestamptz default now()) returns numeric language plpgsql stable security definer set search_path='' as $$
declare resolved numeric(14,2);
begin
 if not public.can_access_branch(target_branch) then raise exception 'You do not have access to this branch';end if;
 select pp.amount into resolved from public.product_prices pp where pp.variant_id=target_variant and pp.price_type=target_price_type and (pp.branch_id=target_branch or pp.branch_id is null) and pp.effective_from<=at_time and (pp.effective_to is null or pp.effective_to>at_time) order by case when pp.branch_id=target_branch then 0 else 1 end,pp.effective_from desc limit 1;
 if resolved is null then raise exception 'No active selling price exists for this product variant';end if;return resolved;end;$$;

create function public.create_customer(customer_name text,kind public.customer_type,company text default null,phone_number text default null,email_address text default null,postal_address text default null,customer_notes text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare new_id uuid;begin if not public.has_permission('customers.create') then raise exception 'You do not have permission to create customers';end if;if char_length(trim(coalesce(customer_name,'')))<2 then raise exception 'Customer name is required';end if;
 insert into public.customers(customer_code,customer_type,name,company_name,phone,email,address,notes,created_by) values(public.next_sales_number('CUS'),kind,trim(customer_name),nullif(trim(company),''),nullif(trim(phone_number),''),nullif(lower(trim(email_address)),''),nullif(trim(postal_address),''),nullif(trim(customer_notes),''),auth.uid()) returning id into new_id;
 insert into public.audit_logs(actor_user_id,action,entity_type,entity_id,metadata) values(auth.uid(),'customer.created','customers',new_id,jsonb_build_object('name',trim(customer_name),'customer_type',kind));return new_id;end;$$;

create function public.update_customer(target_customer uuid,customer_name text,kind public.customer_type,company text default null,phone_number text default null,email_address text default null,postal_address text default null,customer_notes text default null) returns void language plpgsql security definer set search_path='' as $$
declare old_row public.customers%rowtype;begin if not public.has_permission('customers.update') then raise exception 'You do not have permission to update customers';end if;select * into old_row from public.customers where id=target_customer for update;if not found then raise exception 'Customer not found';end if;if old_row.is_walk_in then raise exception 'The Walk-In Customer is a protected system record';end if;
 update public.customers set customer_type=kind,name=trim(customer_name),company_name=nullif(trim(company),''),phone=nullif(trim(phone_number),''),email=nullif(lower(trim(email_address)),''),address=nullif(trim(postal_address),''),notes=nullif(trim(customer_notes),''),updated_by=auth.uid() where id=target_customer;
 insert into public.audit_logs(actor_user_id,action,entity_type,entity_id,old_values,new_values) values(auth.uid(),'customer.updated','customers',target_customer,to_jsonb(old_row)-'created_by',jsonb_build_object('name',trim(customer_name),'customer_type',kind,'phone',phone_number,'email',email_address));end;$$;

create function public.set_customer_active(target_customer uuid,new_active boolean) returns void language plpgsql security definer set search_path='' as $$
declare old_active boolean;walk_in boolean;begin if not public.has_permission('customers.archive') then raise exception 'You do not have permission to archive customers';end if;select is_active,is_walk_in into old_active,walk_in from public.customers where id=target_customer for update;if not found then raise exception 'Customer not found';end if;if walk_in then raise exception 'The Walk-In Customer cannot be archived';end if;
 update public.customers set is_active=new_active,updated_by=auth.uid() where id=target_customer;insert into public.audit_logs(actor_user_id,action,entity_type,entity_id,old_values,new_values) values(auth.uid(),case when new_active then 'customer.reactivated' else 'customer.archived' end,'customers',target_customer,jsonb_build_object('is_active',old_active),jsonb_build_object('is_active',new_active));end;$$;

create function public.create_sale(target_branch uuid,target_customer uuid,due_on date,sale_notes text,sale_discount numeric,discount_reason text,items jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare new_id uuid;entry jsonb;variant uuid;qty numeric;resolved numeric;actual numeric;line_discount numeric;line numeric;subtotal_value numeric(14,2):=0;ptype public.price_type;product_label text;variant_label text;sku_label text;unit_label text;override_reason text;
begin
 if not public.has_permission('sales.create') or not public.can_access_branch(target_branch) then raise exception 'You do not have permission to create a sale for this branch';end if;
 if not exists(select 1 from public.branches where id=target_branch and is_active) then raise exception 'Sales require an active branch';end if;if not exists(select 1 from public.customers where id=target_customer and is_active) then raise exception 'Choose an active customer';end if;
 if jsonb_typeof(items)<>'array' or jsonb_array_length(items)=0 then raise exception 'At least one sale item is required';end if;if exists(select 1 from(select value->>'variant_id' from jsonb_array_elements(items) group by 1 having count(*)>1)d) then raise exception 'Duplicate variants are not allowed';end if;
 if coalesce(sale_discount,0)<0 then raise exception 'Sale discount cannot be negative';end if;if coalesce(sale_discount,0)>0 and not public.has_permission('sales.discount') then raise exception 'You do not have permission to apply discounts';end if;if coalesce(sale_discount,0)>0 and char_length(trim(coalesce(discount_reason,'')))<3 then raise exception 'A discount reason is required';end if;
 insert into public.sales(sale_number,branch_id,customer_id,payment_due_date,notes,created_by) values(public.next_sales_number('SAL'),target_branch,target_customer,due_on,nullif(trim(sale_notes),''),auth.uid()) returning id into new_id;
 for entry in select value from jsonb_array_elements(items) loop
  variant:=(entry->>'variant_id')::uuid;qty:=(entry->>'quantity')::numeric;ptype:=coalesce((entry->>'price_type')::public.price_type,'RETAIL');perform public.validate_inventory_quantity(variant,qty,false);resolved:=public.resolve_selling_price(variant,target_branch,ptype,now());actual:=coalesce((entry->>'unit_price')::numeric,resolved);line_discount:=coalesce((entry->>'discount_amount')::numeric,0);override_reason:=nullif(trim(entry->>'override_reason'),'');
  if actual<0 then raise exception 'Selling price cannot be negative';end if;if actual<>resolved and (not public.has_permission('sales.price_override') or char_length(coalesce(override_reason,''))<3) then raise exception 'You do not have permission to override this price';end if;
  if line_discount>0 and (not public.has_permission('sales.discount') or char_length(trim(coalesce(entry->>'discount_reason','')))<3) then raise exception 'You do not have permission to apply discounts';end if;line:=round(qty*actual,2)-line_discount;if line<0 then raise exception 'A discount cannot exceed the line value';end if;
  select p.name,v.name,v.sku,u.symbol into product_label,variant_label,sku_label,unit_label from public.product_variants v join public.products p on p.id=v.product_id join public.units_of_measure u on u.id=p.unit_of_measure_id where v.id=variant and v.is_active and p.status='ACTIVE';if not found then raise exception 'Choose an active product variant';end if;
  insert into public.sale_items(sale_id,variant_id,quantity,price_type,suggested_unit_price,unit_price,price_override_reason,discount_amount,discount_reason,line_total,product_name_snapshot,variant_name_snapshot,sku_snapshot,unit_snapshot) values(new_id,variant,qty,ptype,resolved,actual,override_reason,line_discount,nullif(trim(entry->>'discount_reason'),''),line,product_label,variant_label,sku_label,unit_label);
  subtotal_value:=subtotal_value+line;
  if actual<>resolved then insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),target_branch,'sale.price_overridden','sale_items',new_id,jsonb_build_object('variant_id',variant,'suggested_price',resolved,'actual_price',actual,'reason',override_reason));end if;
 end loop;
 if subtotal_value-coalesce(sale_discount,0)<0 then raise exception 'Sale discount cannot exceed the sale value';end if;
 update public.sales set subtotal=subtotal_value,discount_amount=coalesce(sale_discount,0),total_amount=subtotal_value-coalesce(sale_discount,0),balance_due=subtotal_value-coalesce(sale_discount,0) where id=new_id;
 if coalesce(sale_discount,0)>0 or exists(select 1 from public.sale_items where sale_id=new_id and discount_amount>0) then insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),target_branch,'sale.discount_applied','sales',new_id,jsonb_build_object('sale_discount',coalesce(sale_discount,0),'reason',discount_reason));end if;
 insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),target_branch,'sale.created','sales',new_id,jsonb_build_object('customer_id',target_customer,'item_count',jsonb_array_length(items),'total_amount',subtotal_value-coalesce(sale_discount,0)));return new_id;
end;$$;

create function public.complete_sale(target_sale uuid,operation_id uuid,initial_payment numeric default 0,method public.supplier_payment_method default null,payment_reference text default null,payment_notes text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare header public.sales%rowtype;customer public.customers%rowtype;item public.sale_items%rowtype;movement uuid;payment_id uuid;paid numeric(14,2):=coalesce(initial_payment,0);new_status public.sale_payment_status;
begin
 if operation_id is null then raise exception 'A completion operation identifier is required';end if;select * into header from public.sales where completion_operation_key=operation_id;if found then return header.id;end if;
 select * into header from public.sales where id=target_sale for update;if not found then raise exception 'Sale not found';end if;if not public.has_permission('sales.complete') or not public.can_access_branch(header.branch_id) then raise exception 'You do not have permission to complete this sale';end if;if header.status<>'DRAFT' then raise exception 'This sale has already been completed';end if;
 select * into customer from public.customers where id=header.customer_id and is_active;if not found then raise exception 'Choose an active customer';end if;if paid<0 or paid>header.total_amount then raise exception 'The payment exceeds the outstanding balance';end if;if customer.is_walk_in and paid<>header.total_amount then raise exception 'A named customer is required for a credit sale';end if;if paid>0 and method is null then raise exception 'Choose a payment method';end if;
 if exists(select 1 from public.sale_items where sale_id=header.id and unit_price<>suggested_unit_price) and not public.has_permission('sales.price_override') then raise exception 'You do not have permission to override this price';end if;if (header.discount_amount>0 or exists(select 1 from public.sale_items where sale_id=header.id and discount_amount>0)) and not public.has_permission('sales.discount') then raise exception 'You do not have permission to apply discounts';end if;
 for item in select * from public.sale_items where sale_id=header.id order by variant_id loop
  perform public.validate_inventory_quantity(item.variant_id,item.quantity,false);movement:=public.inventory_apply_movement(header.branch_id,item.variant_id,'SALE',-item.quantity,'SALE',header.id,header.sale_number,header.notes);update public.sale_items set stock_movement_id=movement where id=item.id;
 end loop;
 if paid>0 then
  insert into public.customer_payments(payment_number,customer_id,sale_id,branch_id,operation_key,amount,payment_method,payment_reference,notes,recorded_by) values(public.next_sales_number('CPY'),header.customer_id,header.id,header.branch_id,operation_id,paid,method,nullif(trim(payment_reference),''),nullif(trim(payment_notes),''),auth.uid()) returning id into payment_id;
  insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.branch_id,'customer_payment.recorded','customer_payments',payment_id,jsonb_build_object('sale_id',header.id,'customer_id',header.customer_id,'amount',paid,'initial_payment',true));
 end if;
 new_status:=case when paid=0 then 'UNPAID'::public.sale_payment_status when paid=header.total_amount then 'PAID'::public.sale_payment_status else 'PARTIALLY_PAID'::public.sale_payment_status end;
 update public.sales set status='COMPLETED',receipt_number=public.next_sales_number('RCP'),completion_operation_key=operation_id,amount_paid=paid,balance_due=total_amount-paid,payment_status=new_status,completed_by=auth.uid(),completed_at=now() where id=header.id;
 insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) select auth.uid(),header.branch_id,'sale.completed','sales',header.id,jsonb_build_object('sale_number',header.sale_number,'receipt_number',receipt_number,'customer_id',header.customer_id,'total',total_amount,'amount_paid',paid,'balance_due',total_amount-paid,'item_count',(select count(*) from public.sale_items where sale_id=header.id)) from public.sales where id=header.id;return header.id;
end;$$;

create function public.record_customer_payment(target_customer uuid,target_sale uuid,target_branch uuid,operation_id uuid,payment_amount numeric,method public.supplier_payment_method,reference text,payment_on timestamptz,payment_notes text) returns uuid language plpgsql security definer set search_path='' as $$
declare header public.sales%rowtype;existing_id uuid;payment_id uuid;paid numeric(14,2);balance numeric(14,2);new_status public.sale_payment_status;
begin if operation_id is null then raise exception 'A payment operation identifier is required';end if;select id into existing_id from public.customer_payments where branch_id=target_branch and operation_key=operation_id;if found then return existing_id;end if;
 if not public.has_permission('customer_payments.create') or not public.can_access_branch(target_branch) then raise exception 'You do not have permission to record this payment';end if;if payment_amount is null or payment_amount<=0 then raise exception 'Payment amount must be greater than zero';end if;
 select * into header from public.sales where id=target_sale for update;if not found then raise exception 'Sale not found';end if;if header.status<>'COMPLETED' then raise exception 'Payments require a completed sale';end if;if header.branch_id<>target_branch or header.customer_id<>target_customer then raise exception 'Payment does not match the sale customer and branch';end if;if payment_amount>header.balance_due then raise exception 'The payment exceeds the outstanding balance';end if;
 insert into public.customer_payments(payment_number,customer_id,sale_id,branch_id,operation_key,amount,payment_method,payment_reference,payment_date,notes,recorded_by) values(public.next_sales_number('CPY'),target_customer,header.id,target_branch,operation_id,payment_amount,method,nullif(trim(reference),''),coalesce(payment_on,now()),nullif(trim(payment_notes),''),auth.uid()) returning id into payment_id;
 paid:=header.amount_paid+payment_amount;balance:=header.total_amount-paid;new_status:=case when balance=0 then 'PAID'::public.sale_payment_status else 'PARTIALLY_PAID'::public.sale_payment_status end;update public.sales set amount_paid=paid,balance_due=balance,payment_status=new_status where id=header.id;
 insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.branch_id,'customer_payment.recorded','customer_payments',payment_id,jsonb_build_object('sale_id',header.id,'customer_id',target_customer,'amount',payment_amount));return payment_id;end;$$;

create function public.reverse_customer_payment(target_payment uuid,reason text) returns void language plpgsql security definer set search_path='' as $$
declare payment public.customer_payments%rowtype;header public.sales%rowtype;paid numeric(14,2);balance numeric(14,2);new_status public.sale_payment_status;
begin select * into payment from public.customer_payments where id=target_payment for update;if not found then raise exception 'Payment not found';end if;if not public.has_permission('customer_payments.reverse') or not public.can_access_branch(payment.branch_id) then raise exception 'You do not have permission to reverse this payment';end if;if payment.status<>'POSTED' then raise exception 'Only a posted payment can be reversed';end if;if char_length(trim(coalesce(reason,'')))<3 then raise exception 'A reversal reason is required';end if;
 select * into header from public.sales where id=payment.sale_id for update;if header.status<>'COMPLETED' then raise exception 'Payment sale is not completed';end if;update public.customer_payments set status='REVERSED',reversed_at=now(),reversed_by=auth.uid(),reversal_reason=trim(reason) where id=payment.id;
 paid:=header.amount_paid-payment.amount;balance:=header.total_amount-paid;new_status:=case when paid=0 then 'UNPAID'::public.sale_payment_status else 'PARTIALLY_PAID'::public.sale_payment_status end;update public.sales set amount_paid=paid,balance_due=balance,payment_status=new_status where id=header.id;
 insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.branch_id,'customer_payment.reversed','customer_payments',payment.id,jsonb_build_object('sale_id',header.id,'amount',payment.amount,'reason',trim(reason)));end;$$;

create function public.cancel_sale(target_sale uuid,reason text) returns void language plpgsql security definer set search_path='' as $$
declare header public.sales%rowtype;item public.sale_items%rowtype;movement uuid;
begin select * into header from public.sales where id=target_sale for update;if not found then raise exception 'Sale not found';end if;if not public.has_permission('sales.cancel') or not public.can_access_branch(header.branch_id) then raise exception 'You do not have permission to cancel this sale';end if;if char_length(trim(coalesce(reason,'')))<3 then raise exception 'A cancellation reason is required';end if;
 if header.status='DRAFT' then update public.sales set status='CANCELLED',cancelled_by=auth.uid(),cancelled_at=now(),cancellation_reason=trim(reason) where id=header.id;
 elsif header.status='COMPLETED' then if exists(select 1 from public.customer_payments where sale_id=header.id and status='POSTED') then raise exception 'Reverse the posted payments before cancelling this sale';end if;
  for item in select * from public.sale_items where sale_id=header.id order by variant_id loop movement:=public.inventory_apply_movement(header.branch_id,item.variant_id,'SALE_REVERSAL',item.quantity,'SALE',header.id,header.sale_number,trim(reason));update public.sale_items set reversal_movement_id=movement where id=item.id;end loop;update public.sales set status='CANCELLED',cancelled_by=auth.uid(),cancelled_at=now(),cancellation_reason=trim(reason) where id=header.id;
 else raise exception 'This sale has already been cancelled';end if;
 insert into public.audit_logs(actor_user_id,branch_id,action,entity_type,entity_id,metadata) values(auth.uid(),header.branch_id,'sale.cancelled','sales',header.id,jsonb_build_object('sale_number',header.sale_number,'reason',trim(reason)));end;$$;

revoke all on function public.next_sales_number(text),public.resolve_selling_price(uuid,uuid,public.price_type,timestamptz),public.create_customer(text,public.customer_type,text,text,text,text,text),public.update_customer(uuid,text,public.customer_type,text,text,text,text,text),public.set_customer_active(uuid,boolean),public.create_sale(uuid,uuid,date,text,numeric,text,jsonb),public.complete_sale(uuid,uuid,numeric,public.supplier_payment_method,text,text),public.record_customer_payment(uuid,uuid,uuid,uuid,numeric,public.supplier_payment_method,text,timestamptz,text),public.reverse_customer_payment(uuid,text),public.cancel_sale(uuid,text) from public;
grant execute on function public.resolve_selling_price(uuid,uuid,public.price_type,timestamptz),public.create_customer(text,public.customer_type,text,text,text,text,text),public.update_customer(uuid,text,public.customer_type,text,text,text,text,text),public.set_customer_active(uuid,boolean),public.create_sale(uuid,uuid,date,text,numeric,text,jsonb),public.complete_sale(uuid,uuid,numeric,public.supplier_payment_method,text,text),public.record_customer_payment(uuid,uuid,uuid,uuid,numeric,public.supplier_payment_method,text,timestamptz,text),public.reverse_customer_payment(uuid,text),public.cancel_sale(uuid,text) to authenticated;
