-- SAT-J Ent Phase 7: authorized, timezone-correct server-side aggregates.
create index sales_completed_reporting_idx on public.sales(branch_id,completed_at) where status='COMPLETED';
create index customer_payments_posted_reporting_idx on public.customer_payments(branch_id,payment_date) where status='POSTED';
create index sale_items_sale_variant_reporting_idx on public.sale_items(sale_id,variant_id);
create index purchases_reporting_idx on public.purchases(branch_id,purchase_date) where status<>'CANCELLED';
create index audit_business_activity_idx on public.audit_logs(branch_id,created_at desc) where branch_id is not null;

create function public.reporting_scope_allowed(target_branch uuid,company_permission text,branch_permission text) returns boolean language sql stable security definer set search_path='' as $$
 select case when target_branch is null then public.has_permission(company_permission) else public.has_permission(branch_permission) and public.can_access_branch(target_branch) end
$$;
revoke all on function public.reporting_scope_allowed(uuid,text,text) from public;

create function public.dashboard_summary(from_date date,to_date date,target_branch uuid default null) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare start_at timestamptz;end_at timestamptz;prior_start timestamptz;prior_end timestamptz;days integer;result jsonb;
begin
 if from_date is null or to_date is null or from_date>to_date or to_date-from_date>731 then raise exception 'Choose a valid reporting date range of no more than two years';end if;
 if not public.reporting_scope_allowed(target_branch,'dashboard.company.read','dashboard.branch.read') then raise exception 'You do not have access to this dashboard scope';end if;
 start_at:=(from_date::timestamp at time zone 'Africa/Accra');end_at:=((to_date+1)::timestamp at time zone 'Africa/Accra');days:=to_date-from_date+1;prior_end:=start_at;prior_start:=start_at-make_interval(days=>days);
 select jsonb_build_object(
  'from',from_date,'to',to_date,'timezone','Africa/Accra',
  'kpis',jsonb_build_object(
   'sales_revenue',(select coalesce(sum(s.total_amount),0) from public.sales s where s.status='COMPLETED' and s.completed_at>=start_at and s.completed_at<end_at and (target_branch is null or s.branch_id=target_branch)),
   'sales_count',(select count(*) from public.sales s where s.status='COMPLETED' and s.completed_at>=start_at and s.completed_at<end_at and (target_branch is null or s.branch_id=target_branch)),
   'units_sold',(select coalesce(sum(i.quantity),0) from public.sale_items i join public.sales s on s.id=i.sale_id where s.status='COMPLETED' and s.completed_at>=start_at and s.completed_at<end_at and (target_branch is null or s.branch_id=target_branch)),
   'collections',case when public.has_permission('customer_payments.read') then (select coalesce(sum(p.amount),0) from public.customer_payments p where p.status='POSTED' and p.payment_date>=start_at and p.payment_date<end_at and (target_branch is null or p.branch_id=target_branch)) else null end,
   'receivables',case when public.has_permission('receivables.read') then (select coalesce(sum(s.balance_due),0) from public.sales s join public.customers c on c.id=s.customer_id where s.status='COMPLETED' and s.balance_due>0 and not c.is_walk_in and (target_branch is null or s.branch_id=target_branch)) else null end,
   'purchase_value',case when public.has_permission('purchases.read') then (select coalesce(sum(p.total_amount),0) from public.purchases p where p.status<>'CANCELLED' and p.purchase_date between from_date and to_date and (target_branch is null or p.branch_id=target_branch)) else null end,
   'supplier_payments',case when public.has_permission('supplier_payments.read') then (select coalesce(sum(p.amount),0) from public.supplier_payments p where p.payment_date between from_date and to_date and (target_branch is null or p.branch_id=target_branch)) else null end,
   'supplier_balance',case when public.has_permission('purchases.read') then (select coalesce(sum(p.balance_due),0) from public.purchases p where p.status<>'CANCELLED' and p.balance_due>0 and (target_branch is null or p.branch_id=target_branch)) else null end,
   'low_stock',case when public.has_permission('inventory.read') then (select count(*) from public.branch_inventory bi where bi.quantity_on_hand>0 and bi.quantity_on_hand<=bi.minimum_stock_level and (target_branch is null or bi.branch_id=target_branch)) else null end,
   'out_of_stock',case when public.has_permission('inventory.read') then (select count(*) from public.branch_inventory bi where bi.quantity_on_hand=0 and (target_branch is null or bi.branch_id=target_branch)) else null end,
   'in_transit',case when public.has_permission('transfers.read') then (select coalesce(sum(i.dispatched_quantity-i.received_quantity),0) from public.stock_transfers t join public.stock_transfer_items i on i.transfer_id=t.id where t.status='DISPATCHED' and (target_branch is null or t.source_branch_id=target_branch or t.destination_branch_id=target_branch)) else null end
  ),
  'prior',jsonb_build_object(
   'sales_revenue',(select coalesce(sum(s.total_amount),0) from public.sales s where s.status='COMPLETED' and s.completed_at>=prior_start and s.completed_at<prior_end and (target_branch is null or s.branch_id=target_branch)),
   'collections',case when public.has_permission('customer_payments.read') then (select coalesce(sum(p.amount),0) from public.customer_payments p where p.status='POSTED' and p.payment_date>=prior_start and p.payment_date<prior_end and (target_branch is null or p.branch_id=target_branch)) else null end,
   'purchase_value',case when public.has_permission('purchases.read') then (select coalesce(sum(p.total_amount),0) from public.purchases p where p.status<>'CANCELLED' and p.purchase_date between (from_date-days) and (from_date-1) and (target_branch is null or p.branch_id=target_branch)) else null end
  ),
  'trend',(select coalesce(jsonb_agg(jsonb_build_object('date',d.day,'sales',coalesce(s.amount,0),'collections',coalesce(c.amount,0)) order by d.day),'[]'::jsonb) from generate_series(from_date,to_date,'1 day'::interval)d(day) left join lateral(select sum(x.total_amount) amount from public.sales x where x.status='COMPLETED' and (x.completed_at at time zone 'Africa/Accra')::date=d.day::date and (target_branch is null or x.branch_id=target_branch))s on true left join lateral(select sum(x.amount) amount from public.customer_payments x where x.status='POSTED' and (x.payment_date at time zone 'Africa/Accra')::date=d.day::date and (target_branch is null or x.branch_id=target_branch) and public.has_permission('customer_payments.read'))c on true),
  'branches',case when public.has_permission('dashboard.company.read') then (select coalesce(jsonb_agg(x order by x.sales_revenue desc),'[]'::jsonb) from(select b.id,b.name,coalesce(sum(s.total_amount),0) sales_revenue,count(s.id) sales_count from public.branches b left join public.sales s on s.branch_id=b.id and s.status='COMPLETED' and s.completed_at>=start_at and s.completed_at<end_at where b.is_active and (target_branch is null or b.id=target_branch) group by b.id,b.name)x) else '[]'::jsonb end,
  'top_products',(select coalesce(jsonb_agg(x order by x.revenue desc),'[]'::jsonb) from(select i.variant_id,i.sku_snapshot sku,i.product_name_snapshot product,i.variant_name_snapshot variant,i.unit_snapshot unit,sum(i.quantity) quantity,sum(i.line_total) revenue from public.sale_items i join public.sales s on s.id=i.sale_id where s.status='COMPLETED' and s.completed_at>=start_at and s.completed_at<end_at and (target_branch is null or s.branch_id=target_branch) group by i.variant_id,i.sku_snapshot,i.product_name_snapshot,i.variant_name_snapshot,i.unit_snapshot order by revenue desc limit 8)x),
  'inventory',case when public.has_permission('inventory.read') then jsonb_build_object('health',(select coalesce(jsonb_object_agg(x.status,x.count),'{}'::jsonb) from(select case when bi.quantity_on_hand=0 then 'OUT_OF_STOCK' when bi.quantity_on_hand<=bi.minimum_stock_level then 'LOW_STOCK' else 'IN_STOCK' end status,count(*) from public.branch_inventory bi where target_branch is null or bi.branch_id=target_branch group by 1)x),'urgent',(select coalesce(jsonb_agg(x order by x.shortfall desc),'[]'::jsonb) from(select bi.id,p.name product,v.name variant,v.sku,b.name branch,bi.quantity_on_hand,bi.minimum_stock_level,(bi.minimum_stock_level-bi.quantity_on_hand) shortfall,u.symbol unit from public.branch_inventory bi join public.branches b on b.id=bi.branch_id join public.product_variants v on v.id=bi.variant_id join public.products p on p.id=v.product_id join public.units_of_measure u on u.id=p.unit_of_measure_id where bi.quantity_on_hand<=bi.minimum_stock_level and (target_branch is null or bi.branch_id=target_branch) order by shortfall desc limit 8)x)) else null end,
  'aging',case when public.has_permission('receivables.read') then (select coalesce(jsonb_object_agg(bucket,amount),'{}'::jsonb) from(select case when s.payment_due_date is null then 'NO_DUE_DATE' when s.payment_due_date>=to_date then 'CURRENT' when to_date-s.payment_due_date between 1 and 30 then 'DAYS_1_30' when to_date-s.payment_due_date between 31 and 60 then 'DAYS_31_60' when to_date-s.payment_due_date between 61 and 90 then 'DAYS_61_90' else 'DAYS_90_PLUS' end bucket,sum(s.balance_due) amount from public.sales s join public.customers c on c.id=s.customer_id where s.status='COMPLETED' and s.balance_due>0 and not c.is_walk_in and (target_branch is null or s.branch_id=target_branch) group by 1)x) else null end,
  'payment_methods',case when public.has_permission('customer_payments.read') then (select coalesce(jsonb_agg(x order by x.amount desc),'[]'::jsonb) from(select p.payment_method method,sum(p.amount) amount from public.customer_payments p where p.status='POSTED' and p.payment_date>=start_at and p.payment_date<end_at and (target_branch is null or p.branch_id=target_branch) group by p.payment_method)x) else null end,
  'purchasing',case when public.has_permission('purchases.read') then (select jsonb_build_object('ordered',count(*) filter(where p.status='ORDERED'),'partial',count(*) filter(where p.status='PARTIALLY_RECEIVED'),'received',count(*) filter(where p.status='RECEIVED'),'awaiting_value',coalesce(sum(p.balance_due) filter(where p.status<>'CANCELLED'),0)) from public.purchases p where (target_branch is null or p.branch_id=target_branch)) else null end,
  'transfers',case when public.has_permission('transfers.read') then (select jsonb_build_object('requested',count(*) filter(where t.status='REQUESTED'),'approved',count(*) filter(where t.status='APPROVED'),'in_transit',count(*) filter(where t.status='DISPATCHED'),'received',count(*) filter(where t.status='RECEIVED' and t.received_at>=start_at and t.received_at<end_at)) from public.stock_transfers t where target_branch is null or t.source_branch_id=target_branch or t.destination_branch_id=target_branch) else null end,
  'activity',(select coalesce(jsonb_agg(x order by x.created_at desc),'[]'::jsonb) from(select a.action,a.entity_type,a.entity_id,a.branch_id,a.created_at from public.audit_logs a where a.action in('sale.completed','customer_payment.recorded','purchase.received','supplier_payment.recorded','transfer.dispatched','transfer.received','inventory.adjustment_completed') and (target_branch is null or a.branch_id=target_branch) order by a.created_at desc limit 12)x)
 ) into result;
 return result;
end;$$;

create function public.reporting_sales(from_date date,to_date date,target_branch uuid default null,row_limit integer default 100,row_offset integer default 0) returns table(sale_id uuid,sale_date date,sale_number text,receipt_number text,branch_id uuid,branch_name text,customer_name text,total_amount numeric,amount_paid numeric,balance_due numeric,payment_status text) language plpgsql stable security definer set search_path='' as $$
begin if from_date is null or to_date is null or from_date>to_date or row_limit not between 1 and 1000 or row_offset<0 then raise exception 'Invalid report filters';end if;if not public.reporting_scope_allowed(target_branch,'reports.company.read','reports.branch.read') then raise exception 'You do not have access to this report scope';end if;return query select s.id,(s.sale_date at time zone 'Africa/Accra')::date,s.sale_number,s.receipt_number,s.branch_id,b.name,c.name,s.total_amount,s.amount_paid,s.balance_due,s.payment_status::text from public.sales s join public.branches b on b.id=s.branch_id join public.customers c on c.id=s.customer_id where s.status='COMPLETED' and (s.completed_at at time zone 'Africa/Accra')::date between from_date and to_date and (target_branch is null or s.branch_id=target_branch) order by s.completed_at desc limit row_limit offset row_offset;end;$$;

create function public.reporting_receivable_aging(as_of date,target_branch uuid default null) returns table(bucket text,amount numeric,sale_count bigint) language plpgsql stable security definer set search_path='' as $$
begin if as_of is null then raise exception 'An as-of date is required';end if;if not public.has_permission('receivables.read') or not public.reporting_scope_allowed(target_branch,'reports.company.read','reports.branch.read') then raise exception 'You do not have access to receivable reporting';end if;return query select case when s.payment_due_date is null then 'NO_DUE_DATE' when s.payment_due_date>=as_of then 'CURRENT' when as_of-s.payment_due_date between 1 and 30 then 'DAYS_1_30' when as_of-s.payment_due_date between 31 and 60 then 'DAYS_31_60' when as_of-s.payment_due_date between 61 and 90 then 'DAYS_61_90' else 'DAYS_90_PLUS' end,sum(s.balance_due),count(*) from public.sales s join public.customers c on c.id=s.customer_id where s.status='COMPLETED' and s.balance_due>0 and not c.is_walk_in and (target_branch is null or s.branch_id=target_branch) group by 1 order by 1;end;$$;

revoke all on function public.dashboard_summary(date,date,uuid),public.reporting_sales(date,date,uuid,integer,integer),public.reporting_receivable_aging(date,uuid) from public;
grant execute on function public.dashboard_summary(date,date,uuid),public.reporting_sales(date,date,uuid,integer,integer),public.reporting_receivable_aging(date,uuid) to authenticated;
